# Generated by Django 5.2 on 2025-05-02 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(verbose_name='Nom')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(verbose_name='Titre')),
                ('contenido', models.TextField(verbose_name='Contenu')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Publication')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Image')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorias', models.ManyToManyField(to='blog.categoria', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
