# Generated by Django 5.2 on 2025-05-02 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 16, 30, 47, 147328, tzinfo=datetime.timezone.utc), verbose_name='Date Publication'),
        ),
    ]
