# Generated by Django 5.2 on 2025-05-02 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_entrada_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Publication'),
        ),
    ]
