# Generated by Django 5.2 on 2025-05-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_entrada_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='categorias',
            field=models.ManyToManyField(related_name='entradas', to='blog.categoria', verbose_name='Catégories'),
        ),
    ]
