# Generated by Django 5.2 on 2025-05-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_proyecto_options_alter_proyecto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='enlace',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Web'),
        ),
    ]
