# Generated by Django 5.2 on 2025-05-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(verbose_name='Nom')),
                ('subtitulo', models.CharField(verbose_name='Sous-Titre')),
                ('descripcion', models.TextField(verbose_name='Description')),
                ('imagen', models.ImageField(upload_to='servicios', verbose_name='Image')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
