# Generated by Django 5.2 on 2025-05-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(unique=True, verbose_name='Clé')),
                ('nombre', models.CharField(verbose_name='Réseau Social')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Lien')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
            ],
            options={
                'verbose_name': 'Lien',
                'verbose_name_plural': 'Liens',
                'ordering': ['nombre'],
            },
        ),
    ]
