# Generated by Django 5.2 on 2025-05-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(verbose_name='Titre')),
                ('contenido', models.TextField(verbose_name='Contenu')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['titulo'],
            },
        ),
    ]
