# Generated by Django 5.2 on 2025-05-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={'ordering': ['orden', 'titulo'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='pagina',
            name='orden',
            field=models.SmallIntegerField(default=0, verbose_name='Position'),
        ),
    ]
